// Resolves boat pier stop IDs for scenic via-searches; rerun when Transitous feed versions change.
import { writeFile } from 'node:fs/promises';
import { SCENIC_HUBS } from '../src/data/scenery.js';
import { distanceKm } from '../src/journey.js';

const headers = { 'User-Agent': 'bodensee-grenzenlos-tools/0.2 (+https://github.com/tcriess/bodensee-grenzenlos)' };
const ids = {};
for (const hub of SCENIC_HUBS) {
  const url = `https://api.transitous.org/api/v1/geocode?${new URLSearchParams({ text: hub.name, type: 'STOP', place: `${hub.lat},${hub.lon}`, placeBias: 10, numResults: 20 })}`;
  const res = await (await fetch(url, { headers })).json();
  const piers = res.filter(r => r.modes?.includes('FERRY') && distanceKm(r, hub) < 2).sort((a, b) => distanceKm(a, hub) - distanceKm(b, hub));
  ids[hub.name] = piers[0]?.id ?? null;
  console.log(hub.name.padEnd(16), piers[0] ? `${piers[0].name} (${distanceKm(piers[0], hub).toFixed(2)} km)` : 'NOT FOUND');
}
await writeFile(new URL('../src/data/hubs.js', import.meta.url),
  `// Generated by tools/resolve-hubs.mjs on ${new Date().toISOString().slice(0, 10)}.\nexport const HUB_STOP_IDS = ${JSON.stringify(ids, null, 2)};\n`);
